import React,{useState} from 'react'
import Loader from './Loader'
import FormField from './FormField'
import Card from './Card';
export default function Home() {
    const [loading, setLoading] = useState(false);
    const [searchtext, setSearchtext] = useState('');
    const RenderData=({data,title})=>{
        if(data?.length > 0){
            return data.map((post)=>{

                 <Card key={post._id} {...post}/>
            })
        }
        return <h1 className='font-inter text-blue-600 uppercase'>{title}</h1>

    }

  return (
    <section>
  <div>
        <h1 className='text-[32px] text-[#222328]font-inter font-extrabold'>The Community Showcase</h1>
        <p className='mt-2 text-md text-[#666e75]'>Browse through a collection of imaginative and visually stunning images generated by dall-e</p>



    </div>
    <div className='mt-10'><FormField/> </div>
    <div className='mt-5 '>
            {
                loading ? <Loader className="flex justify-center items-center"/> : <></>
            }
            {
                searchtext && <span className="font-inter text-xl text-[#666e56]">Showing results for {searchtext}</span>
            }
            <div className='grid grid-cols-1 gap-3'>
                {searchtext ? <RenderData data={[]} title="Not found"/>
                : <RenderData data={[]} title="No posts found"/>}
             

            </div>
         </div>
    </section>
  
  )
}
